[package]
name = "shpank"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
thiserror = "1.0.61"

[dev-dependencies]
rstest = { version = "0.21.0", default-features = false, features = [
    "crate-name",
] }
