[package]
name = "borld"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = { workspace = true }
bevy = "0.14.0-rc.3"
bincode = "1.3.3"
serde = { workspace = true }
shpank = { workspace = true }
